spring:
  application:
    name: Raydium
config:
  check-range-rate: 300000
  check-pool-status-rate: 3600000
  record-pool-details-rate: 3600000
  position:
    id: FGwfdpXfhoSLda7wb7rsPfY9HLBKQmaDCvmeQHggAqpF
    range:
      min: 216
      max: 358
      warn: 0.30
  topic: raydium
logging:
  level:
    web: info
